{% set name = "pyFFTW" %}
{% set version = "0.12.0" %}
{% set sha256 = "60988e823ca75808a26fd79d88dbae1de3699e72a293f812aa4534f8a0a58cb0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<36]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - fftw
    - numpy
    - pip
  run:
    - python
    # only need fftw at run-time if static linking was not used
    - fftw  # [win]
    - {{ pin_compatible('numpy') }}

about:
  home: https://pyfftw.readthedocs.io
  license: BSD or GPL 2
  license_file: LICENSE.txt
  summary: A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.
  doc_url: https://pyfftw.readthedocs.io
  dev_url: https://github.com/pyFFTW/pyFFTW
